---
- name: Reboot Server
  shell: nohup /sbin/shutdown -r now "Ansible updates triggered" > /dev/null </dev/null 2>&1 &
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to come back
  local_action:
      wait_for
      host={{ ansible_host }}
      port={{ ansible_port }}
      timeout=300
      delay=5
  become: false
